inventory_management/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import include
from django.urls import path

urlpatterns = [
    path('', include('pickup.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view(template_name='pickup/registration/login.html'), name="login"),
]

pickup/urls.py
from django.views.generic import TemplateView
from django.urls import path, re_path
from pickup import views

urlpatterns = [
    # Inventory management URLs
    re_path(r'^history/$', views.history, name='history'),
    re_path(r'^active/$', views.active, name='active'),
    re_path(r'^transaction/(\d{4,6}$)', views.transaction, name='transaction'),

    # Home page
    path('home/', views.home, name='home'),
    path('', views.home, name='home'),

    # Signup page
    path('signup/', TemplateView.as_view(template_name="pickup/signup.html"), name='signup')
]

pickup/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime


class Transaction(models.Model):
    transaction_num = models.IntegerField(primary_key=True)
    customer_name = models.CharField(max_length=255, blank=True)
    transaction_date = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True)
    est_pickup_date = models.DateField(blank=True, null=True)
    forfeit_date = models.DateField(blank=True, null=True)

    # The status of the transaction, based on the items or the forfeit boolean

    def status(self):
        if self.forfeit_date is not None:
            return 'Forfeited'
        else:
            results = Item.objects.filter(transaction_num=self.pk)
            if len(results) > 0:
                active = 0
                for item in results:
                    if item.picked_up_on is None:
                        active += 1
                if active > 0:
                    return 'Active'
                else:
                    return 'Completed'
            else:
                return 'No Items'

    def __str__(self):  # __unicode__ on Python 2
        return str(self.pk)

    def final_pickup_date(self):
        if self.status() == 'Completed':

            # Return latest item pickup date
            final_pickup = Item.objects.filter(
                transaction_num=self.pk).order_by('-picked_up_on')[0]
            final_pickup = final_pickup.picked_up_on
            return final_pickup.strftime('%A, %b. %-d, %Y')

    def overdue(self):

        # Only if the transaction is active:

        if self.status() == 'Active' and self.est_pickup_date is not None:

            # If the estimated pickup date is greater than today's date, then
            # it's overdue

            now = datetime.now()
            todays_date = now.strftime('%Y-%m-%d')
            if self.est_pickup_date.strftime('%Y-%m-%d') > todays_date:
                return False
            else:
                return True
        else:
            return False

    def pretty_phone(self):
        if len(self.phone) == 10:
            phone_string = '(' + self.phone[0:3] + ') ' \
                           + self.phone[3:6] + '-' + self.phone[6:10]
            return phone_string
        else:
            return self.phone

    class Meta:
        db_table = 'transaction'


# Create your models here.

class Item(models.Model):
    itemid = models.IntegerField(primary_key=True)
    transaction_num = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    desc = models.CharField(max_length=255)
    picked_up_on = models.DateField(blank=True, null=True)

    def status(self):
        results = \
            Transaction.objects.get(transaction_num=self.transaction_num.pk)
        if self.picked_up_on is not None:
            return 'Picked up %s' \
                   % self.picked_up_on.strftime('%A, %b. %-d, %Y')
        elif results.forfeit_date is not None:
            return 'Forfeited'
        else:
            return 'In Inventory'

    class Meta:

        db_table = 'item'

    def __str__(self):  # __unicode__ on Python 2
        return str(self.desc)

    # Override date string with "Forfeited" if never picked up


class Note(models.Model):
    noteid = models.IntegerField(primary_key=True)
    transaction_num = models.ForeignKey('Transaction',
                                        db_column='transaction_num', on_delete=models.CASCADE)
    content = models.CharField(max_length=255)
    date = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'note'

    def __str__(self):  # __unicode__ on Python 2
        return str(self.noteid)

pickup/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# Sign Up Form
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]
from django import forms
from .models import Transaction, Item

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['transaction_num', 'transaction_date', 'est_pickup_date', 'customer_name', 'phone']

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['transaction_num', 'desc']

pickup/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from django.shortcuts import render
from django.template import RequestContext
from pickup.models import Transaction, Item, Note
from django.db import connection
from django.contrib.auth.models import User
import time
import json
import datetime
from django.utils.timezone import localtime
from django.shortcuts import render
from .forms import TransactionForm, ItemForm
from .models import Transaction, Item
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from pickup.models import Transaction


# Functions used to get info from the DB
# Updating the transaction info pane

def transaction_info(transaction_number):
    pulled_transaction = \
        Transaction.objects.get(transaction_num=transaction_number)
    return (pulled_transaction.status(),
            pulled_transaction.final_pickup_date())


# jQuery functionx

# Used to add items to a transaction, redirects to new transaction.  In
# every view.

def add_form_view(request):
    add_form = TransactionForm()
    if request.GET.get('status') == 'add_transaction':
        transaction_form = TransactionForm(request.GET)
        if transaction_form.is_valid():
            add_new_transaction = transaction_form.save()
            items = request.GET.get('items')

            # Add all of the items to the transaction
            if ',' in items:
                item_lists = items.split(',')
                for item in item_lists:
                    add_new_item = ItemForm({'transaction_num': add_new_transaction.pk, 'desc': item})
                    if add_new_item.is_valid():
                        add_new_item.save()
            else:
                add_new_item = ItemForm({'transaction_num': add_new_transaction.pk, 'desc': items})
                if add_new_item.is_valid():
                    add_new_item.save()

            print()
            print('%s added Transaction # %s' % (request.user, add_new_transaction.transaction_num))
            print()

    return render(request, 'history.html', {'add_form': add_form})



# Delete items and send back the item count

def trash_item(request):
    if request.GET.get('status') == 'trash':
        trash_item = request.GET.get('item_id')
        item_name = Item.objects.get(pk=trash_item)
        print(item_name.transaction_num)

        Item.objects.filter(itemid=trash_item).delete()

        transaction_number = request.GET.get('transaction_number')

        pulled_transaction = \
            Transaction(transaction_num=transaction_number)
        item_count = \
            len(Item.objects.filter(transaction_num=pulled_transaction))

        # transaction_info(transaction_number) is an updated version of the
        # status string

        print()
        print('%s trashed Item # %s (%s)' %
              (request.user, trash_item, item_name))
        print()

        return item_count, transaction_info(transaction_number)


# If we get a request to add items on the transaction page, add it to the DB.

def add_item(request):
    if request.GET.get('status') == 'add_item':

        transaction_number = request.GET.get('transaction_number')
        item_lists = request.GET.get('item_list')

        new_item_ids = []

        def item_id_query():
            cursor = connection.cursor()
            item_id_query = \
                """SELECT itemid FROM item ORDER BY itemid DESC"""
            cursor.execute(item_id_query)
            return cursor.fetchall()[0][0]

        # If a list, add each item.  If not, add the one item available.

        if ',' in item_lists:
            item_lists = item_lists.split(',')
            for item in item_lists:
                pulled_transaction = \
                    Transaction(transaction_num=transaction_number)
                add_new_item = Item(transaction_num=pulled_transaction,
                                    desc=item)
                add_new_item.save()
                new_item_id = item_id_query()
                new_item_ids.append(new_item_id)
        else:

            pulled_transaction = \
                Transaction(transaction_num=transaction_number)
            add_new_item = Item(transaction_num=pulled_transaction,
                                desc=item_lists)
            add_new_item.save()
            new_item_id = item_id_query()
            new_item_ids.append(new_item_id)

        pulled_transaction = \
            Transaction(transaction_num=transaction_number)
        item_count = \
            len(Item.objects.filter(transaction_num=pulled_transaction))

        # Send back the generated itemid(s).
        # Remember, when an item is added, it changes the transaction to active
        # automatically.

        print()
        print('%s trashed Item # %s' % (request.user, trash_item))
        print()

        return new_item_ids, item_count


def add_note(request):
    if request.GET.get('status') == 'add_note':
        blurb = request.GET.get('blurb')
        user_id = request.GET.get('user_id')
        transaction_number = request.GET.get('transaction_number')
        now = datetime.datetime.now()
        pulled_transaction = \
            Transaction(transaction_num=transaction_number)
        pulled_user = User(pk=user_id)
        new_note = Note(transaction_num=pulled_transaction,
                        content=blurb, date=now, user=pulled_user)
        new_note.save()

        # The note that we just added ...

        latest_note = Note.objects.latest('noteid')

        # ... the id ...

        latest_note_date = localtime(latest_note.date)

        # ... the user's first name who added it ...

        note_user = User.objects.get(pk=user_id)
        note_user = note_user.first_name

        # ... and the new note count for the transaction.

        print()
        print('%s added a Note' % request.user)
        print()

        note_count = \
            len(Note.objects.filter(transaction_num=pulled_transaction))

        return (latest_note_date.strftime('%A, %b. %d, %Y, %I:%m %p'),
                note_count, note_user)


# Edit individual items

def edit_item(request):
    if request.GET.get('status') == 'edit_item':
        item_id = request.GET.get('current_item_id')
        new_desc = request.GET.get('new_desc')
        Item.objects.filter(itemid=item_id).update(desc=new_desc)

        print()
        print('%s edited Item # %s' % (request.user, item_id))
        print()


def edit_item_date(request):
    if request.GET.get('status') == 'edit_item_date':
        item_id = request.GET.get('current_item_id')
        new_date = request.GET.get('new_date')
        transaction_number = request.GET.get('transaction_number')
        Item.objects.filter(itemid=item_id).update(picked_up_on=new_date)
        new_item_date = Item.objects.get(itemid=item_id)

        print()
        print('%s changed Item #%s date to %s' % (
            request.user, item_id, new_date))
        print()

        return (new_item_date.status(),
                transaction_info(transaction_number))


# Editing a transaction's information

def edit_transaction(request):
    if request.GET.get('status') == 'edit_transaction':
        transaction_number = request.GET.get('transaction_number')
        edited_transaction_number = \
            request.GET.get('edited_transaction_number')
        transaction_date = request.GET.get('transaction_date')
        est_pickup_date = request.GET.get('est_pickup_date')
        customer_name = request.GET.get('customer_name')
        phone_number = request.GET.get('phone_number')

        returned_data = {
            'transaction_date': transaction_date,
            'est_pickup_date': est_pickup_date,
            'customer_name': customer_name,
            'phone': phone_number,
        }

        # If the transaction number needs to be changed, do this first
        if transaction_number != edited_transaction_number:

            Transaction.objects.filter(transaction_num=transaction_number).update(
                transaction_num=edited_transaction_number)
            pulled_transaction = Transaction.objects.get(
                pk=edited_transaction_number)
            Item.objects.filter(transaction_num_id=transaction_number).update(
                transaction_num_id=pulled_transaction)
            Note.objects.filter(transaction_num_id=transaction_number).update(
                transaction_num_id=pulled_transaction)
            new_transaction_num = edited_transaction_number
        else:
            new_transaction_num = transaction_number

        for entry in returned_data:
            if returned_data[entry] != '':
                print(returned_data[entry])
                if entry == 'transaction_date':

                    Transaction.objects.filter(transaction_num=new_transaction_num).update(
                        transaction_date=returned_data[entry])
                elif entry == 'est_pickup_date':

                    Transaction.objects.filter(transaction_num=new_transaction_num).update(
                        est_pickup_date=returned_data[entry])
                elif entry == 'customer_name':

                    Transaction.objects.filter(transaction_num=new_transaction_num).update(
                        customer_name=returned_data[entry])
                elif entry == 'phone':

                    Transaction.objects.filter(transaction_num=new_transaction_num).update(
                        phone=returned_data[entry])

        return new_transaction_num


# Forfeit or reinstate a transaction

def forfeit(request):
    if request.GET.get('status') == 'forfeit':
        transaction_number = request.GET.get('transaction_number')
        pulled_transaction = \
            Transaction.objects.get(transaction_num=transaction_number)

        # If the transaction is not forfeited, add today's date.  Otherwise,
        # clear it.

pickup/templates/pickup/active.html
{% extends "pickup/base.html" %}

{% block title %}Active{% endblock %}

{% block header %}

{% endblock %}

{% block content %}

<div class="col-md-12 col-centered">
<ul class="nav nav-pills">
  <li class="nav-item"><a class="nav-link active" href="#tab_a" data-toggle="pill">Transactions</a>
  </li>
<li class="nav-item"><a class="nav-link" href="#tab_b" data-toggle="pill">Items</a>
  </li>
</ul>

<div class="tab-content">
<!-- View Tab -->
<div class="tab-pane active" id="tab_a">

    <div class="container-fluid">
    <div class="row">
        <div class="table-responsive">
            <table id="grid" class="table table-condensed table-hover table-striped">
                <thead>
                    <tr>
                        <th data-column-id="transNum" data-filterable="true" data-formatter="link" data-align="center" data-header-align="center">Transaction #</th>
                        <th data-column-id="Customer" data-filterable="true">Customer</th>
                        <th data-column-id="transDate" data-filterable="true">Transaction Date</th>
                        <th data-column-id="Items" data-filterable="true">Items</th>
                        <th data-column-id="Overdue" data-formatter="overdue" data-filterable="true">Overdue</th>
                    </tr>
                </thead>
                <tbody>
                  {% for transaction in transaction_list %}
                    <tr>
                        <td>{{ transaction.transaction_num }}</td>
                        <td>{{ transaction.customer_name }}</td>
                        <td>{{ transaction.transaction_date|date:"c" }}</td>
                        <td>{{ transaction.item_set.count }}</td>
                        <td>{{ transaction.overdue }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
            </table>
        <!--/div-->
    </div>
    </div>
    </div>

</div>

<div class="tab-pane fade" id="tab_b">
    <div class="container-fluid">
    <div class="row">
        <div class="table-responsive">
            <table id="item-grid" class="table table-condensed table-hover table-striped">
                <thead>
                    <tr data-formatter="current_row">
                        <th data-column-id="itemDesc" data-filterable="true" data-align="center" data-header-align="center">Item</th>
                        <th data-column-id="itemCustomer" data-filterable="true">Customer</th>
                        <th data-column-id="itemTransNum" data-formatter="link" data-filterable="true">Transaction #</th>
                        <th data-column-id="itemTransDate" data-filterable="true">Transaction Date</th>
                        <th data-column-id="itemOverdue" data-formatter="itemOverdue" data-filterable="true">Overdue</th>
                    </tr>
                </thead>
                <tbody>
                  {% for i in item_list %}
                    <tr>
                        <td>{{ i.desc }}</td>
                        <td>{{ i.transaction_num.customer_name }}</td>
                        <td>{{ i.transaction_num }}</td>
                        <td>{{ i.transaction_num.transaction_date }}</td>
                        <td>{{ i.transaction_num.overdue }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
            </table>
        <!--/div-->
    </div>
    </div>
    </div>
</div>


</div>



{% endblock %}

{% block custom_scripts %} 

<script>
$("#grid").bootgrid(
{
	formatters: {
        "link": function(column, row)
        {
            return '<a href="/transaction/' + row[column.id] + '">' + row[column.id] + '</a>';
        },
        "overdue": function(column, row)
            {
                if (row[column.id] == "True")
                {
                    return "Yes";
                }
                else
                {
                    return "No";
                
                }
            }
	}
});
$("#item-grid").bootgrid(
{
    formatters: {
            "link": function(column, row)
            {
                return '<a href="/transaction/' + row[column.id] + '">' + row[column.id] + '</a>';
            },
            "itemOverdue": function(column, row)
            {
                if (row[column.id] == "True")
                {
                    return "Yes";
                }
                else
                {
                    return "No";
                
                }
            }
        }
    });
</script>

{% endblock %}

pickup/templates/pickup/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{% block title %}{% endblock %}</title>

    <!-- Load static files -->
    {% load static %}

    {% block css %}
      <!-- Bootstrap -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
      <!-- Bootstrap Icons -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
      <!-- Custom CSS -->
      <link href="{% static 'css/custom.css' %}" type="text/css" rel="stylesheet">
      <!-- pickadate.js CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pickadate@5.0.0-alpha.3/lib/apis/dom/index.min.css">
      <!-- Bootstrap Tagsinput -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-tagsinput@0.7.1/dist/bootstrap-tagsinput.min.css">
      <!-- Bootgrid -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery-bootgrid@1.3.1/dist/jquery.bootgrid.min.css">
      {% endblock %}
  </head>

  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
      {% block nav %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
              <a class="navbar-brand" href="#">Inventory Pickup</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                          <a class="nav-link" href="/home">Home</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="/active">Active</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="/history">History</a>
                      </li>
                  </ul>
              </div>
              <div class="row">
                  <div class="col-md-12 text-right">
                      <span class="user_credentials" id="{{ user.id }}">{{ user.username }} (<a href="/logout">Log out</a>)</span>
                      <br />
                  </div>
              </div>
          </div>
      </nav>
  </div>
  {% endblock %}

  <div class="row">
      <!-- Header text -->
      <div class="col-xs-6">
          <span class="h2">{% block header %} {% endblock %}</span>
      </div>
      <!-- Add Transaction Modal Button -->
      <div class="col-xs-6">
          <span>
              <button type="button" id="add_button" class="btn btn-default btn-md" data-toggle="modal" data-target="#AddTransactionModal">
                  <i class="bi bi-plus-circle"></i> Add Transaction
              </button>
          </span>
      </div>
  </div>

    <br />

    <!-- Add Transaction Modal -->
<!-- Add Transaction Modal -->
<div class="modal fade" id="AddTransactionModal" tabindex="-1" aria-labelledby="AddTransactionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="AddTransactionModalLabel">Add Transaction</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="add_form.reset();"></button>
            </div>
            <div class="modal-body">
                <!-- Form inputs start here -->
                <form name="add_form" id="add_form" class="form-horizontal" method="POST" action="">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_transaction_num" class="form-label">Transaction #</label>
                        <input id="id_transaction_num" name="transaction_num" type="text" class="form-control" pattern="\d*" placeholder="ex: 41111">
                    </div>
                    <div class="mb-3">
                        <label for="id_transaction_date" class="form-label">Transaction Date</label>
                        <input type="text" class="form-control datepicker" id="id_transaction_date" name="transaction_date">
                        <input type="hidden" class="form-control datepicker hidden" id="id_transaction_date_hidden" name="prefix__transaction_date__suffix">
                    </div>
                    <div class="mb-3">
                        <label for="id_est_pickup_date" class="form-label">Est. Pickup Date</label>
                        <input type="text" class="form-control datepicker" id="id_est_pickup_date" name="est_pickup_date">
                        <input type="hidden" class="form-control datepicker hidden" id="id_est_pickup_date_hidden" name="prefix__est_pickup_date__suffix">
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_customer_name" class="form-label">Customer Name</label>
                            <input id="id_customer_name" class="form-control" type="text" title="Enter first name" placeholder="Full Name" name="customer_name">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone" class="form-label">Phone Number</label>
                            <input id="id_phone" pattern="\d*" class="form-control" type="text" name="phone" title="Enter phone number" placeholder="Phone">
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="id_items" class="form-label">Items</label>
                        <input id="id_items" name="items" data-role="tagsinput" class="form-control" />
                        <small id="item_add_comment" class="form-text text-muted">Separate with commas</small>
                    </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="this.form.reset();">Cancel</button>
                <button type="submit" class="btn btn-primary" value="Add" id="add_transaction_button">Add</button>
            </div>
            </form>
        </div>
    </div>
  </div>
</div>



    <div class="container-fluid">
      <div class="row">
      {% block content%}
      {% endblock %}
      </div>
    </div>

    <!-- jQuery -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>

    <!-- Popper Before Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@floating-ui/dom@1.6.13/dist/floating-ui.dom.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@floating-ui/core@1.6.9/dist/floating-ui.core.umd.min.js"></script>

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>

    <!--pickadate.js -->
    <script src="https://cdn.jsdelivr.net/npm/pickadate@5.0.0-alpha.3/builds/index.min.js"></script>

    <!-- Bootstrap Tagsinput -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-tagsinput@0.7.1/dist/bootstrap-tagsinput.min.js"></script>

    <!-- Bootgrid -->
    <script src="https://cdn.jsdelivr.net/npm/jquery-bootgrid@1.3.1/dist/jquery.bootgrid.min.js"></script>

    <!-- Bootstrap Confirmation -->
    <script src="https://cdn.jsdelivr.net/npm/angular-bootstrap-confirm@2.5.1/dist/angular-bootstrap-confirm.min.js"></script>

   {% block custom_scripts %}
   {% endblock %}
</html>

pickup/templates/pickup/home.html
{% extends "pickup/base.html" %}

{% block title %}Home{% endblock %}

{% block header %}{% endblock %}

{% block content %}

<div class="col-12 col-centered">
  {% if overdue_transactions == 1 %}
    <div class="alert alert-danger fade in" role="alert">
      <span class="glyphicon glyphicon-time"></span>
      There is one overdue transaction which needs your attention. <a href="/active" class="alert-link">View it here</a>.
    </div>
  {% elif overdue_transactions > 1 %}
    <div class="alert alert-danger fade in" role="alert">
      <span class="glyphicon glyphicon-time"></span>
      There are {{ overdue_transactions }} overdue transactions which need your attention. <a href="/active" class="alert-link">View them here</a>.
    </div>
  {% endif %}

<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="help-tab" data-bs-toggle="tab" data-bs-target="#help" type="button" role="tab" aria-controls="help" aria-selected="true">Help</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="stats-tab" data-bs-toggle="tab" data-bs-target="#stats" type="button" role="tab" aria-controls="stats" aria-selected="false">Stats</button>
  </li>
</ul>

<div class="tab-content">
  <!-- Help Tab -->
  <div class="tab-pane fade show active" id="help" role="tabpanel" aria-labelledby="help-tab">
    <br />
    <h4>When Do I Use This?</h4>
    <p>Use this app whenever customer items are moved to or from the "Sold" holding area.</p>
    <br />
    <h4>How Do I Do It?</h4>
    <p>
      Click the
      <i class="bi bi-plus-circle"></i> button to add a transaction and its items. The transaction should appear under the 'Active' page.
    </p>
    <br />
    <h4>What If I Have Issues?</h4>
    <p>Send an email to <a href="mailto:paul@paulsolin.com">paul@paulsolin.com</a>, or file a bug at the repository over at <a href="http://github.com/psolin">github.com/psolin</a>.</p>
  </div>

  <!-- Stats Tab -->
  <div class="tab-pane fade" id="stats" role="tabpanel" aria-labelledby="stats-tab">
    <br />
    <p>Stats will go here. Some day.</p>
  </div>
</div>

</div>
{% endblock %}

pickup/templates/pickup/index.html
{% extends "pickup/base.html" %}
{% load i18n %}

{% block title %}Django Registration Test App{% endblock %}

{% block content %}
{% endblock %}

pickup/templates/pickup/profile.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Account Profile{% endblock %}

{% block content %}
{% endblock %}

pickup/templates/pickup/signup.html
{% extends 'pickup/outside_base.html' %}

{% block title %}Sign Page{% endblock title %}

{% block content %} 
    <h2>Sign Page</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
        <br><br>
        <a href="{% url 'home' %}">Home</a>
    </form>
{% endblock content %}